[workspace]
members = [
    "../Gobblet/base65536",
    "../Gobblet/slimnn",
    "../Gobblet/synthesis",
    "../Gobblet/export",
    "../Gobblet/study-connect4",
    "../Gobblet/playground",
    "../Gobblet/gobblet",
    "../Gobblet/wasm_lab",
]